---
abstract: 'prints stack traces with arguments expanded into readable format'
author:
  - 'Sergey Aleynikov <sergey.aleynikov@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: '6.59'
  Test::More: '0'
configure_requires:
  CPAN::Meta: '0'
  ExtUtils::MakeMaker: '6.59'
  Module::Install::CPANfile: '0'
  Module::Install::ReadmeFromPod: '0'
  inc::Module::Install: '0'
dynamic_config: '0'
generated_by: 'Module::Install version 1.19, CPAN::Meta::Converter version 2.150010'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Devel-PrettyTrace
no_index:
  directory:
    - inc
    - t
provides:
  Devel::PrettyTrace:
    file: lib/Devel/PrettyTrace.pm
    version: '0.04'
requires:
  Data::Printer: '0.19'
  List::MoreUtils: '0'
  perl: v5.6.0
resources:
  license: http://opensource.org/licenses/bsd-license.php
version: '0.04'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
